table<-read.csv("household_power_consumption.txt", sep=";", dec = ".", na.strings = "?")
Feb1<-subset(table, table$Date == "1/2/2007")
Feb2<-subset(table, table$Date == "2/2/2007")
Feb12<-rbind(Feb1, Feb2)
datetime<-strptime(paste(Feb12$Date, Feb12$Time), format = "%d/%m/%Y %H:%M:%S")
Feb12x<-cbind(Feb12, datetime)
plot(Feb12x$datetime, Feb12x$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab = "")
lines(Feb12x$datetime, Feb12x$Sub_metering_2, col="red")
lines(Feb12x$datetime, Feb12x$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty=1)
png("plot3.png", h=480, w=480)
plot(Feb12x$datetime, Feb12x$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab = "")
lines(Feb12x$datetime, Feb12x$Sub_metering_2, col="red")
lines(Feb12x$datetime, Feb12x$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty=1)
dev.off()
