table<-read.csv("household_power_consumption.txt", sep=";", dec = ".", na.strings = "?")
Feb1<-subset(table, table$Date == "1/2/2007")
Feb2<-subset(table, table$Date == "2/2/2007")
Feb12<-rbind(Feb1, Feb2)
datetime<-strptime(paste(Feb12$Date, Feb12$Time), format = "%d/%m/%Y %H:%M:%S")
Feb12x<-cbind(Feb12, datetime)
par(mfrow=c(2,2))
plot(Feb12x$datetime, Feb12x$Global_active_power, ylab = "Global Active Power", xlab="", type = "l")
plot(Feb12x$datetime, Feb12x$Voltage, ylab = "Voltage", xlab="datetime", type = "l")
plot(Feb12x$datetime, Feb12x$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab = "")
lines(Feb12x$datetime, Feb12x$Sub_metering_2, col="red")
lines(Feb12x$datetime, Feb12x$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty=1, cex = 0.2, bty = "n")
plot(Feb12x$datetime, Feb12x$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type = "l")
png("plot4.png")
par(mfrow=c(2,2))
plot(Feb12x$datetime, Feb12x$Global_active_power, ylab = "Global Active Power", xlab="", type = "l")
plot(Feb12x$datetime, Feb12x$Voltage, ylab = "Voltage", xlab="datetime", type = "l")
plot(Feb12x$datetime, Feb12x$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab = "")
lines(Feb12x$datetime, Feb12x$Sub_metering_2, col="red")
lines(Feb12x$datetime, Feb12x$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty=1, cex = 0.2, bty = "n")
plot(Feb12x$datetime, Feb12x$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type = "l")
dev.off()