table<-read.csv("household_power_consumption.txt", sep=";", dec = ".", na.strings = "?")
Feb1<-subset(table, table$Date == "1/2/2007")
Feb2<-subset(table, table$Date == "2/2/2007")
Feb12<-rbind(Feb1, Feb2)
datetime<-strptime(paste(Feb12$Date, Feb12$Time), format = "%d/%m/%Y %H:%M:%S")
Feb12x<-cbind(Feb12, datetime)
plot(Feb12x$datetime, Feb12x$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", type = "l")
png("plot2.png", h=480, w=480)
plot(Feb12x$datetime, Feb12x$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", type = "l")
dev.off()