table<-read.csv("household_power_consumption.txt", sep=";", dec = ".", na.strings = "?")
Feb1<-subset(table, table$Date == "1/2/2007")
Feb2<-subset(table, table$Date == "2/2/2007")
Feb12<-rbind(Feb1, Feb2)
strptime(Feb12$Time, format = "")
plot(Feb12$Time, Feb12$Global_active_power, ylab="Global Active Power (kilowatts)", xaxt="n")
axis(side=1, at=c(0, 725, 1450), labels=c("Thu", "Fri", "Sat"))
png("plot2.png")
plot(Feb12$Time, Feb12$Global_active_power, ylab="Global Active Power (kilowatts)", xaxt="n")
axis(side=1, at=c(0, 725, 1450), labels=c("Thu", "Fri", "Sat"))
dev.off()